version: "3.8"
services:
  web:
    command: npm run dev --prefix apps/web
    user: "0:0"
    volumes:
       - ./apps/web:/usr/src/apps/web
  api:
    command: npm run dev --prefix apps/api
    user: "0:0"
    volumes:
       - ./apps/api:/usr/src/apps/api
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 5430:8080
    networks:
      - app
